# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc8c8b68ea6e88546a18bdc61a935fe0cf364ab1816ea0f868c6e9ada44aa6d99be38ef0419fa653508b967a58d6d09f4ecfd829da17b48a55a379924219b88

test:
  secret_key_base: 20ea396934c387275cb06d01dbad753cd81694d66e37927e4435eab683c1e1b122f2d90bf422e31812e4e4bb70f61c49353c695806e0055053251b988adf2b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
